# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('foldername', models.CharField(max_length=100)),
                ('fatherid', models.IntegerField()),
                ('updata', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('folder_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='disk.Folder')),
                ('path', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
            bases=('disk.folder',),
        ),
    ]
