# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='updata',
            new_name='update',
        ),
    ]
