# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-24 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0002_auto_20180216_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='md5',
            field=models.CharField(default='etst', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(upload_to='file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
