# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 02:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disk', '0003_auto_20180224_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
    ]
