# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-14 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(default='<django.db.models.fields.AutoField>', max_length=50)),
                ('birthday', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phonenum', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
