# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20180214_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listroot',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
