# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_listroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listroot',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
