# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-27 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_user_listroot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='listroot',
            field=models.IntegerField(null=True),
        ),
    ]
